name: turismo_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  path: ^1.9.0
  sqflite: ^2.3.3+1
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  image_path: "assets/images/ic_launcher.png"
  android: true
  ios: true
  min_sdk_android: 21
dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
